#!/bin/bash
# 本地 STUN/TURN 测试环境一键安装脚本
# 详细文档见: doc/LOCAL_STUN_TURN_TESTING.md

set -e

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
step()  { echo -e "${BLUE}[STEP]${NC} $1"; }

# 配置
PRIMARY_IP="10.2.120.148"
ALIAS_IP="10.2.120.149"
CONFIG_FILE=~/turnserver.conf
TURN_USER="test"
TURN_PASS="test123"

echo ""
echo "=========================================="
echo "  本地 STUN/TURN 测试环境安装脚本"
echo "=========================================="
echo ""

# 检查是否为 macOS
if [[ "$(uname)" != "Darwin" ]]; then
    error "This script is designed for macOS only"
    exit 1
fi

# 检查 Homebrew
step "1/5 检查 Homebrew..."
if ! command -v brew &> /dev/null; then
    error "Homebrew not installed. Install from: https://brew.sh"
    exit 1
fi
info "Homebrew OK"

# 安装 coturn
step "2/5 安装 Coturn..."
if command -v turnserver &> /dev/null; then
    info "Coturn already installed: $(which turnserver)"
else
    info "Installing coturn..."
    brew install coturn
    info "Coturn installed"
fi

# 安装 stuntman（可选，用于测试）
step "3/5 安装 Stuntman (STUN 测试工具)..."
if command -v stunclient &> /dev/null; then
    info "Stuntman already installed"
else
    info "Installing stuntman..."
    brew install stuntman
    info "Stuntman installed"
fi

# 获取当前 IP
step "4/5 配置网络..."
CURRENT_IP=$(ifconfig en0 | grep "inet " | awk '{print $2}' | head -1)
if [[ -z "$CURRENT_IP" ]]; then
    error "Cannot detect IP address on en0"
    exit 1
fi

# 更新配置中的 IP
PRIMARY_IP="$CURRENT_IP"
# 计算 alias IP（当前 IP 最后一段 +1）
IFS='.' read -r a b c d <<< "$CURRENT_IP"
ALIAS_IP="$a.$b.$c.$((d + 1))"

info "Primary IP: $PRIMARY_IP"
info "Alias IP:   $ALIAS_IP"

# 创建配置文件
step "5/5 创建配置文件..."
cat > "$CONFIG_FILE" << EOF
# Coturn STUN/TURN Server Configuration
# Auto-generated by setup_local_stun.sh
# Date: $(date)

# 双 IP 配置（STUN NAT 检测需要）
listening-ip=$PRIMARY_IP
listening-ip=$ALIAS_IP

# STUN/TURN 端口
listening-port=3478
alt-listening-port=3479

# 中继地址范围（TURN relay）
relay-ip=$PRIMARY_IP
min-port=49152
max-port=65535

# RFC 5780 NAT 行为检测
rfc5780

# 认证配置（TURN 需要）
realm=local
user=$TURN_USER:$TURN_PASS

# 日志
verbose
log-file=stdout

# 禁用 TLS
no-tls
no-dtls

# 指纹
fingerprint
EOF
info "Config created: $CONFIG_FILE"

# 更新启动脚本中的 IP（只更新默认值行，不影响 case 语句）
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
START_SCRIPT="$SCRIPT_DIR/start_local_stun.sh"
if [[ -f "$START_SCRIPT" ]]; then
    sed -i '' "s/^PRIMARY_IP=\"[^\"]*\"/PRIMARY_IP=\"$PRIMARY_IP\"/" "$START_SCRIPT"
    sed -i '' "s/^ALIAS_IP=\"[^\"]*\"/ALIAS_IP=\"$ALIAS_IP\"/" "$START_SCRIPT"
    info "Updated start_local_stun.sh with current IPs"
fi

echo ""
echo "=========================================="
echo "  安装完成！"
echo "=========================================="
echo ""
echo "配置信息："
echo "  Primary IP:  $PRIMARY_IP"
echo "  Alias IP:    $ALIAS_IP"
echo "  STUN Port:   3478, 3479"
echo "  TURN User:   $TURN_USER"
echo "  TURN Pass:   $TURN_PASS"
echo "  Config:      $CONFIG_FILE"
echo ""
echo "使用方法："
echo "  # 启动服务（需要 sudo 添加 IP 别名）："
echo "  ./test/start_local_stun.sh"
echo ""
echo "  # 停止服务："
echo "  pkill turnserver"
echo ""
echo "  # 测试 STUN："
echo "  stunclient $PRIMARY_IP"
echo ""
echo "  # 测试 TURN："
echo "  ./build_cmake/p2p_ping/p2p_ping --stun $PRIMARY_IP --turn $PRIMARY_IP --turn-user $TURN_USER --turn-pass $TURN_PASS -s localhost -n alice -l 5"
echo ""
echo "注意："
echo "  - IP 别名在重启后会丢失，需重新运行 start_local_stun.sh"
echo "  - 详细文档见: doc/LOCAL_STUN_TURN_TESTING.md"
echo ""
