#!/bin/bash
# 本地 STUN/TURN 服务启动脚本
# 安装脚本: test/setup_local_stun.sh
# 详细文档: doc/LOCAL_STUN_TURN_TESTING.md

set -e

# 默认 IP（会被 setup_local_stun.sh 自动更新）
PRIMARY_IP="10.2.120.148"
ALIAS_IP="10.2.120.149"
CONFIG_FILE=~/turnserver.conf

# 从命令行参数读取 IP（优先级高于默认值）
while [[ $# -gt 0 ]]; do
    case $1 in
        --ip) PRIMARY_IP="$2"; shift 2 ;;
        --alias) ALIAS_IP="$2"; shift 2 ;;
        --force) FORCE_CONFIG=1; shift ;;
        --stop) pkill turnserver 2>/dev/null && echo "Stopped" || echo "Not running"; exit 0 ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo "  --ip IP       Primary IP address"
            echo "  --alias IP    Alias IP address"
            echo "  --force       Force regenerate config"
            echo "  --stop        Stop turnserver"
            exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

TURN_USER="test"
TURN_PASS="test123"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 检查 coturn 是否安装
if ! command -v turnserver &> /dev/null; then
    error "coturn not installed. Run: brew install coturn"
    exit 1
fi

# 添加 IP 别名（如果不存在）
if ! ifconfig en0 | grep -q "$ALIAS_IP"; then
    info "Adding IP alias $ALIAS_IP (requires sudo)"
    sudo ifconfig en0 alias "$ALIAS_IP" netmask 255.255.255.0
    info "IP alias added"
else
    info "IP alias $ALIAS_IP already exists"
fi

# 创建配置文件（如果不存在或强制更新）
if [[ ! -f "$CONFIG_FILE" || -n "$FORCE_CONFIG" ]]; then
    info "Creating config file: $CONFIG_FILE"
    cat > "$CONFIG_FILE" << EOF
# Coturn STUN/TURN Server Configuration
# Auto-generated by start_local_stun.sh

# 双 IP 配置（STUN NAT 检测需要）
listening-ip=$PRIMARY_IP
listening-ip=$ALIAS_IP

# STUN/TURN 端口
listening-port=3478
alt-listening-port=3479

# 中继地址范围（TURN relay）
relay-ip=$PRIMARY_IP
min-port=49152
max-port=65535

# RFC 5780 NAT 行为检测
rfc5780

# 认证配置（TURN 需要）
realm=local
user=$TURN_USER:$TURN_PASS

# 日志
verbose
log-file=stdout

# 禁用 TLS
no-tls
no-dtls

# 指纹
fingerprint
EOF
fi

# 停止已有实例
pkill turnserver 2>/dev/null && info "Stopped existing turnserver" || true
sleep 1

# 启动 turnserver
info "Starting turnserver..."
turnserver -c "$CONFIG_FILE" &
sleep 2

# 验证
if pgrep turnserver > /dev/null; then
    info "Coturn started successfully"
    echo ""
    echo "=== STUN/TURN Server Info ==="
    echo "  Primary IP:  $PRIMARY_IP"
    echo "  Alias IP:    $ALIAS_IP"
    echo "  Ports:       3478, 3479"
    echo "  TURN User:   $TURN_USER"
    echo "  TURN Pass:   $TURN_PASS"
    echo ""
    echo "=== Test Commands ==="
    echo "  # STUN only:"
    echo "  ./build_cmake/p2p_ping/p2p_ping --stun $PRIMARY_IP -s localhost -n alice -l 5"
    echo ""
    echo "  # STUN + TURN:"
    echo "  ./build_cmake/p2p_ping/p2p_ping --stun $PRIMARY_IP --turn $PRIMARY_IP --turn-user $TURN_USER --turn-pass $TURN_PASS -s localhost -n alice -l 5"
    echo ""
    
    # 快速 STUN 测试
    if command -v stunclient &> /dev/null; then
        echo "=== Quick STUN Test ==="
        stunclient "$PRIMARY_IP"
    fi
else
    error "Failed to start turnserver"
    exit 1
fi
