/*
 * Auto-generated language strings
 */

#include ".LANG.h"

/* 字符串表 */
const char* lang_en[LA_NUM] = {
    [LA_W0] = "[Trickle] Sent",  /* SID:1 */
    [LA_W1] = "[Trickle] TCP send failed",  /* SID:2 */
    [LA_W2] = "ACK processed",  /* SID:3 */
    [LA_W3] = "Added Host candidate",  /* SID:4 */
    [LA_W4] = "Added Remote Candidate",  /* SID:5 */
    [LA_W5] = "address",  /* SID:6 */
    [LA_W6] = "address(es)",  /* SID:7 */
    [LA_W7] = "and",  /* SID:8 */
    [LA_W8] = "as",  /* SID:9 */
    [LA_W9] = "Attempt",  /* SID:10 */
    [LA_W10] = "Attempting Simultaneous Open to",  /* SID:11 */
    [LA_W11] = "attempts, switching to RELAY",  /* SID:12 */
    [LA_W12] = "Authenticated successfully",  /* SID:13 */
    [LA_W13] = "Authentication failed",  /* SID:14 */
    [LA_W14] = "Auto-send answer",  /* SID:15 */
    [LA_W15] = "Bind failed",  /* SID:16 */
    [LA_W16] = "Bound to",  /* SID:17 */
    [LA_W17] = "bytes",  /* SID:18 */
    [LA_W18] = "cache",  /* SID:19 */
    [LA_W19] = "candidate pairs",  /* SID:20 */
    [LA_W20] = "candidates",  /* SID:21 */
    [LA_W21] = "Cannot add Srflx candidate: realloc failed (OOM)",  /* SID:22 */
    [LA_W22] = "COMPACT: registering",  /* SID:23 */
    [LA_W23] = "Connected to server",  /* SID:24 */
    [LA_W24] = "Data stored in recv buffer",  /* SID:25 */
    [LA_W25] = "Detecting...",  /* SID:26 */
    [LA_W26] = "Detection completed",  /* SID:27 */
    [LA_W27] = "Discarded",  /* SID:28 */
    [LA_W28] = "Entered READY state, starting NAT punch and candidate sync",  /* SID:29 */
    [LA_W29] = "Entered REGISTERED state",  /* SID:30 */
    [LA_W30] = "expected",  /* SID:31 */
    [LA_W31] = "Failed to allocate",  /* SID:32 */
    [LA_W32] = "Failed to create UDP socket on port",  /* SID:33 */
    [LA_W33] = "Failed to resolve",  /* SID:34 */
    [LA_W34] = "Failed to resolve TURN server:",  /* SID:35 */
    [LA_W35] = "Failed to send candidates, will retry",  /* SID:36 */
    [LA_W36] = "Field",  /* SID:37 */
    [LA_W37] = "Formed check list with",  /* SID:38 */
    [LA_W38] = "forwarded",  /* SID:39 */
    [LA_W39] = "from",  /* SID:40 */
    [LA_W40] = "Full Cone NAT",  /* SID:41 */
    [LA_W41] = "Gathered",  /* SID:42 */
    [LA_W42] = "Gathered Relay Candidate",  /* SID:43 */
    [LA_W43] = "Gathered Srflx Candidate",  /* SID:44 */
    [LA_W44] = "giving up",  /* SID:45 */
    [LA_W45] = "Initialized:",  /* SID:46 */
    [LA_W46] = "Invalid magic",  /* SID:47 */
    [LA_W47] = "Invalid read state",  /* SID:48 */
    [LA_W48] = "is empty or too short",  /* SID:49 */
    [LA_W49] = "is now online",  /* SID:50 */
    [LA_W50] = "LAN peer confirmed",  /* SID:51 */
    [LA_W51] = "len",  /* SID:52 */
    [LA_W52] = "Local address detection done",  /* SID:53 */
    [LA_W53] = "Mapped address",  /* SID:54 */
    [LA_W54] = "Max register attempts reached",  /* SID:55 */
    [LA_W55] = "more pairs",  /* SID:56 */
    [LA_W56] = "NAT probe retry",  /* SID:57 */
    [LA_W57] = "NAT probe sent to",  /* SID:58 */
    [LA_W58] = "NAT probe timeout, type unknown",  /* SID:59 */
    [LA_W59] = "NAT punch failed, no TURN server configured",  /* SID:60 */
    [LA_W60] = "NAT punch failed, server has no relay support",  /* SID:61 */
    [LA_W61] = "NAT punch failed, using server relay",  /* SID:62 */
    [LA_W62] = "no (cached)",  /* SID:63 */
    [LA_W63] = "Nomination successful! Using",  /* SID:64 */
    [LA_W64] = "online",  /* SID:65 */
    [LA_W65] = "Open Internet (No NAT)",  /* SID:66 */
    [LA_W66] = "Out-of-window packet discarded",  /* SID:67 */
    [LA_W67] = "Packet queued",  /* SID:68 */
    [LA_W68] = "Packet too large",  /* SID:69 */
    [LA_W69] = "Passive peer learned remote ID",  /* SID:70 */
    [LA_W70] = "path",  /* SID:71 */
    [LA_W71] = "Peer",  /* SID:72 */
    [LA_W72] = "Peer is on a different subnet",  /* SID:73 */
    [LA_W73] = "Peer is on the same subnet as",  /* SID:74 */
    [LA_W74] = "Peer offline",  /* SID:75 */
    [LA_W75] = "Peer offline, waiting for peer to come online",  /* SID:76 */
    [LA_W76] = "Peer online",  /* SID:77 */
    [LA_W77] = "Peer online, waiting for PEER_INFO(seq=1)",  /* SID:78 */
    [LA_W78] = "port busy, trying random port",  /* SID:79 */
    [LA_W79] = "Port Restricted Cone NAT",  /* SID:80 */
    [LA_W80] = "priority",  /* SID:81 */
    [LA_W81] = "Processing",  /* SID:82 */
    [LA_W82] = "PUB",  /* SID:83 */
    [LA_W83] = "Published",  /* SID:84 */
    [LA_W84] = "PUBSUB (PUB): gathering candidates, waiting for STUN before publishing",  /* SID:85 */
    [LA_W85] = "PUBSUB (SUB): waiting for offer from any peer",  /* SID:86 */
    [LA_W86] = "PUNCH: Received from",  /* SID:87 */
    [LA_W87] = "PUNCH_ACK: Received from",  /* SID:88 */
    [LA_W88] = "PUNCHING: Attempt",  /* SID:89 */
    [LA_W89] = "Received ACK",  /* SID:90 */
    [LA_W90] = "Received New Remote Candidate",  /* SID:91 */
    [LA_W91] = "Received remote candidate",  /* SID:92 */
    [LA_W92] = "Received route probe from",  /* SID:93 */
    [LA_W93] = "Received signal from",  /* SID:94 */
    [LA_W94] = "Received unknown packet type",  /* SID:95 */
    [LA_W95] = "Received valid signal from",  /* SID:96 */
    [LA_W96] = "recv error",  /* SID:97 */
    [LA_W97] = "Registering",  /* SID:98 */
    [LA_W98] = "RELAY: sent initial offer with",  /* SID:99 */
    [LA_W99] = "RELAY: waiting for incoming offer from any peer",  /* SID:100 */
    [LA_W100] = "Reliable transport initialized",  /* SID:101 */
    [LA_W101] = "Requested",  /* SID:102 */
    [LA_W102] = "Resent",  /* SID:103 */
    [LA_W103] = "resetting",  /* SID:104 */
    [LA_W104] = "Restricted Cone NAT",  /* SID:105 */
    [LA_W105] = "role",  /* SID:106 */
    [LA_W106] = "RTT updated",  /* SID:107 */
    [LA_W107] = "Same subnet detected but LAN shortcut disabled",  /* SID:108 */
    [LA_W108] = "Same subnet detected, sent ROUTE_PROBE to",  /* SID:109 */
    [LA_W109] = "Send window full, dropping packet",  /* SID:110 */
    [LA_W110] = "Sending",  /* SID:111 */
    [LA_W111] = "Sending Allocate Request to",  /* SID:112 */
    [LA_W112] = "Sent ANSWER",  /* SID:113 */
    [LA_W113] = "Sent answer to",  /* SID:114 */
    [LA_W114] = "Sent candidates (cached, peer offline)",  /* SID:115 */
    [LA_W115] = "Sent candidates, forwarded",  /* SID:116 */
    [LA_W116] = "Sent connect",  /* SID:117 */
    [LA_W117] = "Sent route probe to",  /* SID:118 */
    [LA_W118] = "Server error",  /* SID:119 */
    [LA_W119] = "Server storage full, waiting for peer to come online",  /* SID:120 */
    [LA_W120] = "Skipping local Host candidates",  /* SID:121 */
    [LA_W121] = "START: Punching to",  /* SID:122 */
    [LA_W122] = "Storage full",  /* SID:123 */
    [LA_W123] = "SUB",  /* SID:124 */
    [LA_W124] = "Success",  /* SID:125 */
    [LA_W125] = "SUCCESS: Hole punched! Connected to",  /* SID:126 */
    [LA_W126] = "Symmetric NAT (port-random)",  /* SID:127 */
    [LA_W127] = "Test",  /* SID:128 */
    [LA_W128] = "Time:",  /* SID:129 */
    [LA_W129] = "timed out",  /* SID:130 */
    [LA_W130] = "Timeout",  /* SID:131 */
    [LA_W131] = "Timeout (no response)",  /* SID:132 */
    [LA_W132] = "TIMEOUT: Connection lost",  /* SID:133 */
    [LA_W133] = "TIMEOUT: Punch failed after",  /* SID:134 */
    [LA_W134] = "to",  /* SID:135 */
    [LA_W135] = "UDP Blocked (STUN unreachable)",  /* SID:136 */
    [LA_W136] = "UDP hole-punch probing remote candidates",  /* SID:137 */
    [LA_W137] = "Unknown",  /* SID:138 */
    [LA_W138] = "Unknown ACK status",  /* SID:139 */
    [LA_W139] = "Unknown signaling mode",  /* SID:140 */
    [LA_W140] = "Unsupported (no STUN/probe configured)",  /* SID:141 */
    [LA_W141] = "Updating Gist field",  /* SID:142 */
    [LA_W142] = "Waiting for peer",  /* SID:143 */
    [LA_W143] = "while discarding",  /* SID:144 */
    [LA_W144] = "while reading payload",  /* SID:145 */
    [LA_W145] = "while reading sender",  /* SID:146 */
    [LA_W146] = "will be retried by p2p_update()",  /* SID:147 */
    [LA_W147] = "with candidates",  /* SID:148 */
    [LA_W148] = "with server",  /* SID:149 */
    [LA_W149] = "yes",  /* SID:150 */
    [LA_S0] = "1 candidate to",  /* SID:151 */
    [LA_S1] = "[DTLS] Handshake complete",  /* SID:152 */
    [LA_S2] = "[OpenSSL] DTLS handshake completed",  /* SID:153 */
    [LA_S3] = "[SCTP] usrsctp wrapper initialized (skeleton)",  /* SID:154 */
    [LA_S4] = "[Trickle] TCP not connected, skipping single candidate send",  /* SID:155 */
    [LA_S5] = "Added Remote Candidate",  /* SID:156 */
    [LA_S6] = "Allocation successful!",  /* SID:157 */
    [LA_S7] = "Answer already present, skipping offer re-publish",  /* SID:158 */
    [LA_S8] = "Base64 decode failed",  /* SID:159 */
    [LA_S9] = "Bind failed",  /* SID:160 */
    [LA_S10] = "cached",  /* SID:161 */
    [LA_S11] = "Channel ID validation failed",  /* SID:162 */
    [LA_S12] = "COMPACT mode requires explicit remote_peer_id",  /* SID:163 */
    [LA_S13] = "Connection closed by server",  /* SID:164 */
    [LA_S14] = "Connection closed while discarding",  /* SID:165 */
    [LA_S15] = "Connection closed while reading payload",  /* SID:166 */
    [LA_S16] = "Connection closed while reading sender",  /* SID:167 */
    [LA_S17] = "Detecting local network addresses",  /* SID:168 */
    [LA_S18] = "Detection completed",  /* SID:169 */
    [LA_S19] = "ERROR: No remote candidates to punch",  /* SID:171 */
    [LA_S20] = "Error: p2p_ice_send_local_candidate called in non-RELAY mode",  /* SID:172 */
    [LA_S21] = "Failed to allocate ACK payload buffer",  /* SID:173 */
    [LA_S22] = "Failed to allocate discard buffer, closing connection",  /* SID:174 */
    [LA_S23] = "Failed to build STUN request",  /* SID:175 */
    [LA_S24] = "Failed to connect to signaling server",  /* SID:176 */
    [LA_S25] = "Failed to send header",  /* SID:177 */
    [LA_S26] = "Failed to send payload",  /* SID:178 */
    [LA_S27] = "Failed to send target name",  /* SID:179 */
    [LA_S28] = "forwarded",  /* SID:180 */
    [LA_S29] = "from",  /* SID:181 */
    [LA_S30] = "Gist GET failed",  /* SID:182 */
    [LA_S31] = "Host Candidate",  /* SID:183 */
    [LA_S32] = "Invalid channel_id format (security risk)",  /* SID:184 */
    [LA_S33] = "Invalid signaling mode in configuration",  /* SID:185 */
    [LA_S34] = "Mapped address",  /* SID:186 */
    [LA_S35] = "need",  /* SID:187 */
    [LA_S36] = "No auth_key provided, using default key (insecure)",  /* SID:188 */
    [LA_S37] = "no pong for",  /* SID:189 */
    [LA_S38] = "offer with",  /* SID:190 */
    [LA_S39] = "Out of memory",  /* SID:192 */
    [LA_S40] = "payload of message type",  /* SID:193 */
    [LA_S41] = "priority",  /* SID:194 */
    [LA_S42] = "PUBSUB mode requires gh_token and gist_id",  /* SID:195 */
    [LA_S43] = "received",  /* SID:196 */
    [LA_S44] = "relay",  /* SID:197 */
    [LA_S45] = "Relay Candidate",  /* SID:198 */
    [LA_S46] = "RELAY/COMPACT mode requires server_host",  /* SID:199 */
    [LA_S47] = "request to",  /* SID:200 */
    [LA_S48] = "resuming",  /* SID:201 */
    [LA_S49] = "SCTP (usrsctp) requested but library not linked",  /* SID:202 */
    [LA_S50] = "sending ACK",  /* SID:203 */
    [LA_S51] = "Sent authentication request to peer",  /* SID:204 */
    [LA_S52] = "Signal payload deserialization failed",  /* SID:205 */
    [LA_S53] = "Srflx Candidate",  /* SID:206 */
    [LA_S54] = "STUN server",  /* SID:207 */
    [LA_S55] = "Test",  /* SID:208 */
    [LA_S56] = "to",  /* SID:209 */
    [LA_S57] = "total sent",  /* SID:210 */
    [LA_S58] = "type",  /* SID:211 */
    [LA_S59] = "Using",  /* SID:212 */
    [LA_S60] = "via local",  /* SID:213 */
    [LA_S61] = "waiting for",  /* SID:214 */
    [LA_S62] = "waiting for peer to come online",  /* SID:215 */
    [LA_S63] = "with",  /* SID:216 */
    [LA_F0] = "[DTLS] Handshake failed: %s (-0x%04x)",  /* SID:217 */
    [LA_F1] = "[DTLS] ssl_setup failed: -0x%x",  /* SID:218 */
    [LA_F2] = "[PseudoTCP] congestion detected, new ssthresh: %u, cwnd: %u",  /* SID:219 */
    [LA_F3] = "[SCTP] received encapsulated packet, length %d",  /* SID:220 */
    [LA_F4] = "[SCTP] sending %d bytes",  /* SID:221 */
};
