/*
 * Auto-generated language strings
 */

#include ".LANG.h"

/* Embedded cn language table */
static const char* lang_cn[LA_NUM] = {
    [LA_W0] = "[Trickle] Sent",  /* SID:1 new */
    [LA_W1] = "[Trickle] TCP send failed",  /* SID:2 new */
    [LA_W2] = "ACK processed",  /* SID:3 new */
    [LA_W3] = "Added Host candidate",  /* SID:4 new */
    [LA_W4] = "Added Remote Candidate",  /* SID:5 new */
    [LA_W5] = "address",  /* SID:6 new */
    [LA_W6] = "address(es)",  /* SID:7 new */
    [LA_W7] = "and",  /* SID:8 new */
    [LA_W8] = "as",  /* SID:9 new */
    [LA_W9] = "Attempt",  /* SID:10 new */
    [LA_W10] = "Attempting Simultaneous Open to",  /* SID:11 new */
    [LA_W11] = "attempts, switching to RELAY",  /* SID:12 new */
    [LA_W12] = "Authenticated successfully",  /* SID:13 new */
    [LA_W13] = "Authentication failed",  /* SID:14 new */
    [LA_W14] = "Auto-send answer",  /* SID:15 new */
    [LA_W15] = "Bind failed",  /* SID:16 new */
    [LA_W16] = "Bound to",  /* SID:17 new */
    [LA_W17] = "bytes",  /* SID:18 new */
    [LA_W18] = "cache",  /* SID:19 new */
    [LA_W19] = "candidate pairs",  /* SID:20 new */
    [LA_W20] = "candidates",  /* SID:21 new */
    [LA_W21] = "Cannot add Srflx candidate: realloc failed (OOM)",  /* SID:22 new */
    [LA_W22] = "COMPACT: registering",  /* SID:23 new */
    [LA_W23] = "Connected to server",  /* SID:24 new */
    [LA_W24] = "Data stored in recv buffer",  /* SID:25 new */
    [LA_W25] = "Detecting...",  /* SID:26 new */
    [LA_W26] = "Detection completed",  /* SID:27 new */
    [LA_W27] = "Discarded",  /* SID:28 new */
    [LA_W28] = "Entered READY state, starting NAT punch and candidate sync",  /* SID:29 new */
    [LA_W29] = "Entered REGISTERED state",  /* SID:30 new */
    [LA_W30] = "expected",  /* SID:31 new */
    [LA_W31] = "Failed to allocate",  /* SID:32 new */
    [LA_W32] = "Failed to create UDP socket on port",  /* SID:33 new */
    [LA_W33] = "Failed to resolve",  /* SID:34 new */
    [LA_W34] = "Failed to resolve TURN server:",  /* SID:35 new */
    [LA_W35] = "Failed to send candidates, will retry",  /* SID:36 new */
    [LA_W36] = "Field",  /* SID:37 new */
    [LA_W37] = "Formed check list with",  /* SID:38 new */
    [LA_W38] = "forwarded",  /* SID:39 new */
    [LA_W39] = "from",  /* SID:40 new */
    [LA_W40] = "Full Cone NAT",  /* SID:41 new */
    [LA_W41] = "Gathered",  /* SID:42 new */
    [LA_W42] = "Gathered Relay Candidate",  /* SID:43 new */
    [LA_W43] = "Gathered Srflx Candidate",  /* SID:44 new */
    [LA_W44] = "giving up",  /* SID:45 new */
    [LA_W45] = "Initialized:",  /* SID:46 new */
    [LA_W46] = "Invalid magic",  /* SID:47 new */
    [LA_W47] = "Invalid read state",  /* SID:48 new */
    [LA_W48] = "is empty or too short",  /* SID:49 new */
    [LA_W49] = "is now online",  /* SID:50 new */
    [LA_W50] = "LAN peer confirmed",  /* SID:51 new */
    [LA_W51] = "len",  /* SID:52 new */
    [LA_W52] = "Local address detection done",  /* SID:53 new */
    [LA_W53] = "Mapped address",  /* SID:54 new */
    [LA_W54] = "Max register attempts reached",  /* SID:55 new */
    [LA_W55] = "more pairs",  /* SID:56 new */
    [LA_W56] = "NAT probe retry",  /* SID:57 new */
    [LA_W57] = "NAT probe sent to",  /* SID:58 new */
    [LA_W58] = "NAT probe timeout, type unknown",  /* SID:59 new */
    [LA_W59] = "NAT punch failed, no TURN server configured",  /* SID:60 new */
    [LA_W60] = "NAT punch failed, server has no relay support",  /* SID:61 new */
    [LA_W61] = "NAT punch failed, using server relay",  /* SID:62 new */
    [LA_W62] = "no (cached)",  /* SID:63 new */
    [LA_W63] = "Nomination successful! Using",  /* SID:64 new */
    [LA_W64] = "online",  /* SID:65 new */
    [LA_W65] = "Open Internet (No NAT)",  /* SID:66 new */
    [LA_W66] = "Out-of-window packet discarded",  /* SID:67 new */
    [LA_W67] = "Packet queued",  /* SID:68 new */
    [LA_W68] = "Packet too large",  /* SID:69 new */
    [LA_W69] = "Passive peer learned remote ID",  /* SID:70 new */
    [LA_W70] = "path",  /* SID:71 new */
    [LA_W71] = "Peer",  /* SID:72 new */
    [LA_W72] = "Peer is on a different subnet",  /* SID:73 new */
    [LA_W73] = "Peer is on the same subnet as",  /* SID:74 new */
    [LA_W74] = "Peer offline",  /* SID:75 new */
    [LA_W75] = "Peer offline, waiting for peer to come online",  /* SID:76 new */
    [LA_W76] = "Peer online",  /* SID:77 new */
    [LA_W77] = "Peer online, waiting for PEER_INFO(seq=1)",  /* SID:78 new */
    [LA_W78] = "port busy, trying random port",  /* SID:79 new */
    [LA_W79] = "Port Restricted Cone NAT",  /* SID:80 new */
    [LA_W80] = "priority",  /* SID:81 new */
    [LA_W81] = "Processing",  /* SID:82 new */
    [LA_W82] = "PUB",  /* SID:83 new */
    [LA_W83] = "Published",  /* SID:84 new */
    [LA_W84] = "PUBSUB (PUB): gathering candidates, waiting for STUN before publishing",  /* SID:85 new */
    [LA_W85] = "PUBSUB (SUB): waiting for offer from any peer",  /* SID:86 new */
    [LA_W86] = "PUNCH: Received from",  /* SID:87 new */
    [LA_W87] = "PUNCH_ACK: Received from",  /* SID:88 new */
    [LA_W88] = "PUNCHING: Attempt",  /* SID:89 new */
    [LA_W89] = "Received ACK",  /* SID:90 new */
    [LA_W90] = "Received New Remote Candidate",  /* SID:91 new */
    [LA_W91] = "Received remote candidate",  /* SID:92 new */
    [LA_W92] = "Received route probe from",  /* SID:93 new */
    [LA_W93] = "Received signal from",  /* SID:94 new */
    [LA_W94] = "Received unknown packet type",  /* SID:95 new */
    [LA_W95] = "Received valid signal from",  /* SID:96 new */
    [LA_W96] = "recv error",  /* SID:97 new */
    [LA_W97] = "Registering",  /* SID:98 new */
    [LA_W98] = "RELAY: sent initial offer with",  /* SID:99 new */
    [LA_W99] = "RELAY: waiting for incoming offer from any peer",  /* SID:100 new */
    [LA_W100] = "Reliable transport initialized",  /* SID:101 new */
    [LA_W101] = "Requested",  /* SID:102 new */
    [LA_W102] = "Resent",  /* SID:103 new */
    [LA_W103] = "resetting",  /* SID:104 new */
    [LA_W104] = "Restricted Cone NAT",  /* SID:105 new */
    [LA_W105] = "role",  /* SID:106 new */
    [LA_W106] = "RTT updated",  /* SID:107 new */
    [LA_W107] = "Same subnet detected but LAN shortcut disabled",  /* SID:108 new */
    [LA_W108] = "Same subnet detected, sent ROUTE_PROBE to",  /* SID:109 new */
    [LA_W109] = "Send window full, dropping packet",  /* SID:110 new */
    [LA_W110] = "Sending",  /* SID:111 new */
    [LA_W111] = "Sending Allocate Request to",  /* SID:112 new */
    [LA_W112] = "Sent ANSWER",  /* SID:113 new */
    [LA_W113] = "Sent answer to",  /* SID:114 new */
    [LA_W114] = "Sent candidates (cached, peer offline)",  /* SID:115 new */
    [LA_W115] = "Sent candidates, forwarded",  /* SID:116 new */
    [LA_W116] = "Sent connect",  /* SID:117 new */
    [LA_W117] = "Sent route probe to",  /* SID:118 new */
    [LA_W118] = "Server error",  /* SID:119 new */
    [LA_W119] = "Server storage full, waiting for peer to come online",  /* SID:120 new */
    [LA_W120] = "Skipping local Host candidates",  /* SID:121 new */
    [LA_W121] = "START: Punching to",  /* SID:122 new */
    [LA_W122] = "Storage full",  /* SID:123 new */
    [LA_W123] = "SUB",  /* SID:124 new */
    [LA_W124] = "Success",  /* SID:125 new */
    [LA_W125] = "SUCCESS: Hole punched! Connected to",  /* SID:126 new */
    [LA_W126] = "Symmetric NAT (port-random)",  /* SID:127 new */
    [LA_W127] = "Test",  /* SID:128 new */
    [LA_W128] = "Time:",  /* SID:129 new */
    [LA_W129] = "timed out",  /* SID:130 new */
    [LA_W130] = "Timeout",  /* SID:131 new */
    [LA_W131] = "Timeout (no response)",  /* SID:132 new */
    [LA_W132] = "TIMEOUT: Connection lost",  /* SID:133 new */
    [LA_W133] = "TIMEOUT: Punch failed after",  /* SID:134 new */
    [LA_W134] = "to",  /* SID:135 new */
    [LA_W135] = "UDP Blocked (STUN unreachable)",  /* SID:136 new */
    [LA_W136] = "UDP hole-punch probing remote candidates",  /* SID:137 new */
    [LA_W137] = "Unknown",  /* SID:138 new */
    [LA_W138] = "Unknown ACK status",  /* SID:139 new */
    [LA_W139] = "Unknown signaling mode",  /* SID:140 new */
    [LA_W140] = "Unsupported (no STUN/probe configured)",  /* SID:141 new */
    [LA_W141] = "Updating Gist field",  /* SID:142 new */
    [LA_W142] = "Waiting for peer",  /* SID:143 new */
    [LA_W143] = "while discarding",  /* SID:144 new */
    [LA_W144] = "while reading payload",  /* SID:145 new */
    [LA_W145] = "while reading sender",  /* SID:146 new */
    [LA_W146] = "will be retried by p2p_update()",  /* SID:147 new */
    [LA_W147] = "with candidates",  /* SID:148 new */
    [LA_W148] = "with server",  /* SID:149 new */
    [LA_W149] = "yes",  /* SID:150 new */
    [LA_S0] = "1 candidate to",  /* SID:151 new */
    [LA_S1] = "[DTLS] Handshake complete",  /* SID:152 new */
    [LA_S2] = "[OpenSSL] DTLS handshake completed",  /* SID:153 new */
    [LA_S3] = "[SCTP] usrsctp wrapper initialized (skeleton)",  /* SID:154 new */
    [LA_S4] = "[Trickle] TCP not connected, skipping single candidate send",  /* SID:155 new */
    [LA_S5] = "Added Remote Candidate",  /* SID:156 new */
    [LA_S6] = "Allocation successful!",  /* SID:157 new */
    [LA_S7] = "Answer already present, skipping offer re-publish",  /* SID:158 new */
    [LA_S8] = "Base64 decode failed",  /* SID:159 new */
    [LA_S9] = "Bind failed",  /* SID:160 new */
    [LA_S10] = "cached",  /* SID:161 new */
    [LA_S11] = "Channel ID validation failed",  /* SID:162 new */
    [LA_S12] = "COMPACT mode requires explicit remote_peer_id",  /* SID:163 new */
    [LA_S13] = "Connection closed by server",  /* SID:164 new */
    [LA_S14] = "Connection closed while discarding",  /* SID:165 new */
    [LA_S15] = "Connection closed while reading payload",  /* SID:166 new */
    [LA_S16] = "Connection closed while reading sender",  /* SID:167 new */
    [LA_S17] = "Detecting local network addresses",  /* SID:168 new */
    [LA_S18] = "Detection completed",  /* SID:169 new */
    [LA_S19] = "ERROR: No remote candidates to punch",  /* SID:171 new */
    [LA_S20] = "Error: p2p_ice_send_local_candidate called in non-RELAY mode",  /* SID:172 new */
    [LA_S21] = "Failed to allocate ACK payload buffer",  /* SID:173 new */
    [LA_S22] = "Failed to allocate discard buffer, closing connection",  /* SID:174 new */
    [LA_S23] = "Failed to build STUN request",  /* SID:175 new */
    [LA_S24] = "Failed to connect to signaling server",  /* SID:176 new */
    [LA_S25] = "Failed to send header",  /* SID:177 new */
    [LA_S26] = "Failed to send payload",  /* SID:178 new */
    [LA_S27] = "Failed to send target name",  /* SID:179 new */
    [LA_S28] = "forwarded",  /* SID:180 new */
    [LA_S29] = "from",  /* SID:181 new */
    [LA_S30] = "Gist GET failed",  /* SID:182 new */
    [LA_S31] = "Host Candidate",  /* SID:183 new */
    [LA_S32] = "Invalid channel_id format (security risk)",  /* SID:184 new */
    [LA_S33] = "Invalid signaling mode in configuration",  /* SID:185 new */
    [LA_S34] = "Mapped address",  /* SID:186 new */
    [LA_S35] = "need",  /* SID:187 new */
    [LA_S36] = "No auth_key provided, using default key (insecure)",  /* SID:188 new */
    [LA_S37] = "no pong for",  /* SID:189 new */
    [LA_S38] = "offer with",  /* SID:190 new */
    [LA_S39] = "Out of memory",  /* SID:192 new */
    [LA_S40] = "payload of message type",  /* SID:193 new */
    [LA_S41] = "priority",  /* SID:194 new */
    [LA_S42] = "PUBSUB mode requires gh_token and gist_id",  /* SID:195 new */
    [LA_S43] = "received",  /* SID:196 new */
    [LA_S44] = "relay",  /* SID:197 new */
    [LA_S45] = "Relay Candidate",  /* SID:198 new */
    [LA_S46] = "RELAY/COMPACT mode requires server_host",  /* SID:199 new */
    [LA_S47] = "request to",  /* SID:200 new */
    [LA_S48] = "resuming",  /* SID:201 new */
    [LA_S49] = "SCTP (usrsctp) requested but library not linked",  /* SID:202 new */
    [LA_S50] = "sending ACK",  /* SID:203 new */
    [LA_S51] = "Sent authentication request to peer",  /* SID:204 new */
    [LA_S52] = "Signal payload deserialization failed",  /* SID:205 new */
    [LA_S53] = "Srflx Candidate",  /* SID:206 new */
    [LA_S54] = "STUN server",  /* SID:207 new */
    [LA_S55] = "Test",  /* SID:208 new */
    [LA_S56] = "to",  /* SID:209 new */
    [LA_S57] = "total sent",  /* SID:210 new */
    [LA_S58] = "type",  /* SID:211 new */
    [LA_S59] = "Using",  /* SID:212 new */
    [LA_S60] = "via local",  /* SID:213 new */
    [LA_S61] = "waiting for",  /* SID:214 new */
    [LA_S62] = "waiting for peer to come online",  /* SID:215 new */
    [LA_S63] = "with",  /* SID:216 new */
    [LA_F0] = "[DTLS] Handshake failed: %s (-0x%04x)",  /* SID:217 new */
    [LA_F1] = "[DTLS] ssl_setup failed: -0x%x",  /* SID:218 new */
    [LA_F2] = "[PseudoTCP] congestion detected, new ssthresh: %u, cwnd: %u",  /* SID:219 new */
    [LA_F3] = "[SCTP] received encapsulated packet, length %d",  /* SID:220 new */
    [LA_F4] = "[SCTP] sending %d bytes",  /* SID:221 new */
};
