/*
 * 多语言支持
 *
 * 提供中英文双语支持，所有日志和提示信息可切换语言显示
 *
 * 编译选项：
 *   -DP2P_ENABLE_CHINESE  启用中文支持（默认禁用以减少二进制体积）
 */

#ifndef P2P_LANG_H
#define P2P_LANG_H

#include <p2p.h>

#ifdef __cplusplus
extern "C" {
#endif

/* 消息 ID 枚举 */
typedef enum {

    /* 通用: 错误信息 */
    MSG_ERROR_BIND,
    MSG_ERROR_TIMEOUT,
    MSG_ERROR_NO_MEMORY,

    /* P2P 主模块相关 */
    MSG_P2P_PUBSUB_REQUIRES_AUTH,
    MSG_P2P_RELAY_REQUIRES_SERVER,
    MSG_P2P_INVALID_MODE,
    MSG_P2P_UDP_SOCKET_FAILED,
    MSG_P2P_DTLS_NOT_LINKED,
    MSG_P2P_OPENSSL_NOT_LINKED,
    MSG_P2P_SCTP_NOT_LINKED,
    MSG_P2P_COMPACT_NEEDS_PEER_ID,
    MSG_P2P_COMPACT_HOST_CAND,
    MSG_P2P_COMPACT_REGISTERING,
    MSG_P2P_WITH_N_CANDS,
    MSG_P2P_RELAY_SERVER_FAILED,
    MSG_P2P_RELAY_OFFER_SENT,
    MSG_P2P_RELAY_WAITING,
    MSG_P2P_PUBSUB_PUB_GATHERING,
    MSG_P2P_PUBSUB_SUB_WAITING,
    MSG_P2P_UNKNOWN_MODE,
    MSG_P2P_AUTH_OK,
    MSG_P2P_AUTH_FAIL,
    MSG_P2P_UNKNOWN_PKT,
    MSG_P2P_SAME_SUBNET_PROBE,
    MSG_P2P_SAME_SUBNET_DISABLED,
    MSG_P2P_NAT_FAIL_RELAY,
    MSG_P2P_NAT_FAIL_NO_RELAY,
    MSG_P2P_NAT_FAIL_NO_TURN,
    MSG_P2P_CANDS_SENT_FWD,
    MSG_P2P_CANDS_SENT_CACHED,
    MSG_P2P_SERVER_FULL_WAIT,
    MSG_P2P_CANDS_SEND_FAILED,
    MSG_P2P_OFFER_PUBLISHED,
    MSG_P2P_OFFER_RESENT,
    MSG_P2P_OFFER_WITH_CANDS,
    
     /* NAT 打洞相关 */
    MSG_NAT_PUNCH_ERROR_NO_CAND,
    MSG_NAT_PUNCH_START,
    MSG_NAT_PUNCH_CANDIDATES,
    MSG_NAT_PUNCH_RECEIVED,
    MSG_NAT_PUNCH_ACK_RECEIVED,
    MSG_NAT_PUNCH_SUCCESS,
    MSG_NAT_PUNCH_ATTEMPTS,
    MSG_NAT_PUNCH_TIME,
    MSG_NAT_PUNCH_TIMEOUT,
    MSG_NAT_PUNCH_SWITCH_RELAY,
    MSG_NAT_PUNCH_PUNCHING,
    MSG_NAT_PUNCH_TO,
    MSG_NAT_PUNCH_CONN_LOST,
    MSG_NAT_PUNCH_NO_PONG,
    
    /* NAT 检测相关 */
    MSG_NAT_DETECTION_START,
    MSG_NAT_DETECTION_COMPLETED,

    /* NAT 类型名称（用于 p2p_nat_type_str） */
    MSG_NAT_TYPE_DETECTING,       /* 检测中 */
    MSG_NAT_TYPE_TIMEOUT,         /* 超时（无响应）*/
    MSG_NAT_TYPE_UNKNOWN,         /* 未知 */
    MSG_NAT_TYPE_OPEN,            /* 无 NAT / 公网直连 */
    MSG_NAT_TYPE_FULL_CONE,       /* 完全锥形 NAT */
    MSG_NAT_TYPE_RESTRICTED,      /* 受限锥形 NAT */
    MSG_NAT_TYPE_PORT_RESTRICTED, /* 端口受限锥形 NAT */
    MSG_NAT_TYPE_SYMMETRIC,       /* 对称型 NAT */
    MSG_NAT_TYPE_BLOCKED,         /* UDP 不可达 */
    MSG_NAT_TYPE_UNSUPPORTED,     /* 不支持（未配置 STUN/探测端口）*/
    
    /* TCP 打洞相关 */
    MSG_TCP_SIMULTANEOUS_OPEN,
    MSG_TCP_FALLBACK_PORT,
    MSG_TCP_BOUND_TO,
    
    /* ROUTE 模块相关 */
    MSG_ROUTE_DETECT_START,
    MSG_ROUTE_DETECT_DONE,
    MSG_ROUTE_ADDRS,
    MSG_ROUTE_SAME_SUBNET,
    MSG_ROUTE_VIA,
    MSG_ROUTE_DIFF_SUBNET,
    MSG_ROUTE_PROBE_SENT,
    MSG_ROUTE_PROBE_RECV,
    MSG_ROUTE_PROBE_ACK_SENT,
    MSG_ROUTE_LAN_CONFIRMED,

    /* COMPACT 信令相关 */
    MSG_COMPACT_RECEIVED_FIN,
    MSG_COMPACT_TOTAL_CANDIDATES,
    MSG_COMPACT_REGISTERING,
    MSG_COMPACT_WITH_SERVER,
    MSG_COMPACT_SERVER_ERROR,
    MSG_COMPACT_CACHE,
    MSG_COMPACT_RELAY,
    MSG_COMPACT_ALREADY_READY,
    MSG_COMPACT_ENTERED_REGISTERED,
    MSG_COMPACT_PEER_ONLINE,
    MSG_COMPACT_PEER_OFFLINE,
    MSG_COMPACT_BASE,
    MSG_COMPACT_ENTERED_READY,
    MSG_COMPACT_MAX_ATTEMPTS,
    MSG_COMPACT_ATTEMPT,
    MSG_COMPACT_WITH,
    MSG_COMPACT_TOTAL_SENT,
    
    /* RELAY 信令相关 */
    MSG_RELAY_CONNECT_ACK,
    MSG_RELAY_ANSWER_SENT,
    MSG_RELAY_FORWARD_RECEIVED,
    MSG_RELAY_CONNECTED_TO,
    MSG_RELAY_AS,
    MSG_RELAY_SEND_HEADER_FAILED,
    MSG_RELAY_SEND_TARGET_FAILED,
    MSG_RELAY_SEND_PAYLOAD_FAILED,
    MSG_RELAY_SENT_CONNECT,
    MSG_RELAY_REQUEST,
    MSG_RELAY_BYTES,
    MSG_RELAY_SENT_ANSWER,
    MSG_RELAY_WAITING_PEER,
    MSG_RELAY_TIMED_OUT,
    MSG_RELAY_GIVING_UP,
    MSG_RELAY_CONNECTION_CLOSED,
    MSG_RELAY_RECV_ERROR,
    MSG_RELAY_INVALID_MAGIC,
    MSG_RELAY_EXPECTED,
    MSG_RELAY_RESETTING,
    MSG_RELAY_ALLOC_ACK_FAILED,
    MSG_RELAY_CONN_CLOSED_SENDER,
    MSG_RELAY_WHILE_READING_SENDER,
    MSG_RELAY_ALLOC_FAILED,
    MSG_RELAY_CONN_CLOSED_PAYLOAD,
    MSG_RELAY_WHILE_READING_PAYLOAD,
    MSG_RELAY_RECEIVED_ACK,
    MSG_RELAY_PEER_ONLINE,
    MSG_RELAY_FORWARDED,
    MSG_RELAY_PEER_OFFLINE,
    MSG_RELAY_CACHED,
    MSG_RELAY_STORAGE_FULL,
    MSG_RELAY_WAITING_PEER_ONLINE,
    MSG_RELAY_UNKNOWN_ACK_STATUS,
    MSG_RELAY_PASSIVE_LEARNED,
    MSG_RELAY_FROM_MSG,
    MSG_RELAY_PEER,
    MSG_RELAY_IS_NOW_ONLINE,
    MSG_RELAY_RECEIVED,
    MSG_RELAY_RESUMING,
    MSG_RELAY_RECEIVED_SIGNAL,
    MSG_RELAY_ALLOC_DISCARD_FAILED,
    MSG_RELAY_CONN_CLOSED_DISCARD,
    MSG_RELAY_WHILE_DISCARDING,
    MSG_RELAY_DISCARDED,
    MSG_RELAY_PAYLOAD_OF_TYPE,
    MSG_RELAY_INVALID_STATE,
    
    /* PUBSUB 信令相关 */
    MSG_PUBSUB_NO_AUTH_KEY,
    MSG_PUBSUB_INVALID_CHANNEL,
    MSG_PUBSUB_INITIALIZED,
    MSG_PUBSUB_ROLE_PUB,
    MSG_PUBSUB_ROLE_SUB,
    MSG_PUBSUB_BASE64_FAILED,
    MSG_PUBSUB_RECEIVED_SIGNAL,
    MSG_PUBSUB_DESERIALIZE_FAILED,
    MSG_PUBSUB_CHANNEL_VALIDATION_FAILED,
    MSG_PUBSUB_ANSWER_PRESENT,
    MSG_PUBSUB_UPDATING_GIST,
    MSG_PUBSUB_GET_FAILED,
    MSG_PUBSUB_FIELD,
    MSG_PUBSUB_FIELD_EMPTY,
    MSG_PUBSUB_PROCESSING,
    MSG_PUBSUB_ROLE,
    MSG_PUBSUB_RECEIVED_REMOTE_CAND,
    MSG_PUBSUB_TYPE,
    MSG_PUBSUB_ADDRESS,
    MSG_PUBSUB_AUTO_SEND_ANSWER,

    /* ICE 相关 */
    MSG_ICE_GATHERED_SRFLX,
    MSG_ICE_GATHERED_RELAY,
    MSG_ICE_NOMINATION_SUCCESS,
    MSG_ICE_REMOTE_CANDIDATE_ADDED,
    MSG_ICE_CONNECTIVITY_CHECK,
    MSG_ICE_FORMED_CHECKLIST,
    MSG_ICE_CANDIDATE_PAIRS,
    MSG_ICE_AND,
    MSG_ICE_MORE_PAIRS,
    MSG_ICE_ERROR_NON_RELAY,
    MSG_ICE_TRICKLE_TCP_NOT_CONNECTED,
    MSG_ICE_TRICKLE_TCP_FAILED,
    MSG_ICE_WILL_RETRY,
    MSG_ICE_TRICKLE_SENT,
    MSG_ICE_ONE_CANDIDATE,
    MSG_ICE_ONLINE,
    MSG_ICE_YES,
    MSG_ICE_NO_CACHED,
    MSG_ICE_GATHERED,
    MSG_ICE_HOST_CANDIDATE,
    MSG_ICE_REQUESTED,
    MSG_ICE_SRFLX_CANDIDATE,
    MSG_ICE_FROM,
    MSG_ICE_RELAY_CANDIDATE,
    MSG_ICE_RECEIVED_REMOTE,
    MSG_ICE_USING,
    MSG_ICE_PATH,
    MSG_ICE_SENT_ANSWER,
    MSG_ICE_AUTH_SENT,
    
    /* STUN 相关 */
    MSG_STUN_TEST,
    MSG_STUN_MAPPED_ADDRESS,
    MSG_STUN_PRIORITY,
    MSG_STUN_SRFLX_ADD_FAILED,
    MSG_STUN_SUCCESS,
    MSG_STUN_NEED,
    MSG_STUN_RESOLVE_FAILED,
    MSG_STUN_SERVER,
    MSG_STUN_SENDING,
    MSG_STUN_TO,
    MSG_STUN_LEN,
    MSG_STUN_REQUEST_FAILED,
    
    /* TURN 相关 */
    MSG_TURN_SENDING_ALLOC,
    MSG_TURN_RESOLVE_FAILED,
    MSG_TURN_ALLOC_SUCCESS,
    
    /* ARQ 可靠传输相关 */
    MSG_RELIABLE_INIT,
    MSG_RELIABLE_WINDOW_FULL,
    MSG_RELIABLE_PKT_TOO_LARGE,
    MSG_RELIABLE_PKT_QUEUED,
    MSG_RELIABLE_OUT_OF_WINDOW,
    MSG_RELIABLE_DATA_STORED,
    MSG_RELIABLE_RTT_UPDATE,
    MSG_RELIABLE_ACK_PROCESSED,

    /* PseudoTCP 传输层 */
    MSG_PSEUDOTCP_CONGESTION,  /* 检测到拥塞 */
    
    /* COMPACT 模式 NAT 探测相关 */
    MSG_COMPACT_NAT_PROBE_SENT,     /* NAT_PROBE 已发送 */
    MSG_COMPACT_NAT_PROBE_RETRY,    /* NAT_PROBE 重试 */
    MSG_COMPACT_NAT_PROBE_TIMEOUT,  /* NAT_PROBE 超时，无法确定类型 */
    MSG_COMPACT_NAT_OPEN,           /* 无 NAT（公网直连）*/
    MSG_COMPACT_NAT_CONE,           /* 锥形 NAT（端口一致）*/
    MSG_COMPACT_NAT_SYMMETRIC,      /* 对称 NAT（端口随机）*/

    /* DTLS/MbedTLS 传输层 */
    MSG_DTLS_SETUP_FAIL,       /* ssl_setup 失败 */
    MSG_DTLS_HANDSHAKE_DONE,   /* 握手成功 */
    MSG_DTLS_HANDSHAKE_FAIL,   /* 握手失败 */

    /* DTLS/OpenSSL 传输层 */
    MSG_OPENSSL_HANDSHAKE_DONE, /* DTLS 握手完成 */

    /* SCTP 传输层 */
    MSG_SCTP_INIT,   /* 初始化骨架 */
    MSG_SCTP_SEND,   /* 发送数据（verbose）*/
    MSG_SCTP_RECV,   /* 收到数据包（verbose）*/

    MSG_COUNT  /* 消息总数 */
} p2p_msg_id_t;

/* 内部函数：设置当前语言（通过 p2p_config_t.language 配置） */
void p2p_set_language(p2p_language_t lang);

/* 获取消息文本（使用全局当前语言）*/
const char* p2p_msg(p2p_msg_id_t id);

/* 获取消息文本（显式指定语言）*/
const char* p2p_msg_lang(p2p_msg_id_t id, p2p_language_t lang);

/* 便捷宏 */
#define MSG(id)           p2p_msg(id)
#define MSG_LANG(id, lng) p2p_msg_lang(id, lng)

#ifdef __cplusplus
}
#endif

#endif /* P2P_LANG_H */
