/*
 * Auto-generated language strings
 */

#include "LANG.h"

int LA_server;

/* 字符串表 */
static const char* s_lang_en[LA_NUM] = {
    [LA_W1] = "disabled",  /* SID:1 */
    [LA_W2] = "enabled",  /* SID:2 */
    [LA_S3] = "[TCP] User list truncated (too many users)\n",  /* SID:3 */
    [LA_S233] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:233 */
    [LA_S120] = "Enable data relay support (COMPACT mode fallback)",  /* SID:120 */
    [LA_S121] = "Enable MSG RPC support",  /* SID:121 */
    [LA_S122] = "NAT type detection port (0=disabled)",  /* SID:122 */
    [LA_S4] = "Received shutdown signal, exiting gracefully...",  /* SID:4 */
    [LA_S5] = "Shutting down...\n",  /* SID:5 */
    [LA_S123] = "Signaling server listen port (TCP+UDP)",  /* SID:123 */
    [LA_S124] = "Use Chinese language",  /* SID:124 */
    [LA_F6] = "%s accepted, '%s' -> '%s', ses_id=%llu\n",  /* SID:6 */
    [LA_F7] = "%s accepted, peer='%s', ses_id=%llu\n",  /* SID:7 */
    [LA_F8] = "%s accepted, seq=%u, ses_id=%llu\n",  /* SID:8 */
    [LA_F9] = "%s for unknown ses_id=%llu\n",  /* SID:9 */
    [LA_F10] = "%s forwarded: '%s' -> '%s', sid=%u (ses_id=%llu)\n",  /* SID:10 */
    [LA_F11] = "%s forwarded: '%s' -> '%s', sid=%u, msg=%u (ses_id=%llu)\n",  /* SID:11 */
    [LA_F12] = "%s from '%.*s': new instance(old=%u new=%u), resetting session\n",  /* SID:12 */
    [LA_F13] = "%s new sid=%u > pending sid=%u (responding=%d), canceling old RPC (ses_id=%llu)\n",  /* SID:13 */
    [LA_F14] = "%s retransmit during RESP phase, ignoring, sid=%u (ses_id=%llu)\n",  /* SID:14 */
    [LA_F15] = "%s retransmit, resend ACK, sid=%u (ses_id=%llu)\n",  /* SID:15 */
    [LA_F16] = "%s: RPC complete for '%s', sid=%u (ses_id=%llu)\n",  /* SID:16 */
    [LA_F17] = "%s: accepted, local='%.*s', remote='%.*s', inst_id=%u, cands=%d\n",  /* SID:17 */
    [LA_F18] = "%s: accepted, releasing slot for '%s' -> '%s'\n",  /* SID:18 */
    [LA_F19] = "%s: accepted, ses_id=%llu, sid=%u, code=%u, len=%d\n",  /* SID:19 */
    [LA_F20] = "%s: accepted, ses_id=%llu, sid=%u, msg=%u, len=%d\n",  /* SID:20 */
    [LA_F21] = "%s: accepted, ses_id=%llu, sid=%u\n",  /* SID:21 */
    [LA_F22] = "%s: bad payload(len=%zu)\n",  /* SID:22 */
    [LA_F23] = "%s: confirmed '%s', retries=%d (ses_id=%llu)\n",  /* SID:23 */
    [LA_F24] = "%s: data too large (len=%d)\n",  /* SID:24 */
    [LA_F25] = "%s: invalid instance_id=0 from %s\n",  /* SID:25 */
    [LA_F26] = "%s: invalid relay flag from client\n",  /* SID:26 */
    [LA_F27] = "%s: invalid seq=%u\n",  /* SID:27 */
    [LA_F28] = "%s: invalid session_id=%llu or sid=%u\n",  /* SID:28 */
    [LA_F29] = "%s: no matching pending msg (sid=%u)\n",  /* SID:29 */
    [LA_F30] = "%s: no matching pending msg (sid=%u, expected=%u)\n",  /* SID:30 */
    [LA_F31] = "%s: obsolete sid=%u (current=%u), ignoring\n",  /* SID:31 */
    [LA_F32] = "%s: obsolete sid=%u (last=%u) in IDLE state, ignoring\n",  /* SID:32 */
    [LA_F33] = "%s: peer '%s' not online for session_id=%llu\n",  /* SID:33 */
    [LA_F34] = "%s: peer '%s' not online, rejecting sid=%u\n",  /* SID:34 */
    [LA_F35] = "%s: requester not found for ses_id=%llu\n",  /* SID:35 */
    [LA_F135] = "%s: reset '%.*s'(disconnected) session for re-pairing\n",  /* SID:135 */
    [LA_F36] = "%s: unknown session_id=%llu\n",  /* SID:36 */
    [LA_F37] = "%s: waiting for peer '%.*s' to register\n",  /* SID:37 */
    [LA_F38] = "Addr changed for '%s', but first info packet was abandoned (ses_id=%llu)\n",  /* SID:38 */
    [LA_F39] = "Addr changed for '%s', defer notification until first ACK (ses_id=%llu)\n",  /* SID:39 */
    [LA_F40] = "Addr changed for '%s', deferred notifying '%s' (ses_id=%llu)\n",  /* SID:40 */
    [LA_F41] = "Addr changed for '%s', notifying '%s' (ses_id=%llu)\n",  /* SID:41 */
    [LA_F42] = "Cannot relay %s: ses_id=%llu (peer unavailable)\n",  /* SID:42 */
    [LA_F43] = "% Goodbye!\n",  /* SID:43 */
    [LA_F44] = "Invalid port number %d (range: 1-65535)\n",  /* SID:44 */
    [LA_F45] = "Invalid probe port %d (range: 0-65535)\n",  /* SID:45 */
    [LA_F46] = "MSG_REQ peer timeout after %d retries, sending timeout error to '%s', sid=%u (ses_id=%llu)\n",  /* SID:46 */
    [LA_F47] = "MSG_REQ peer went offline, sending error to '%s', sid=%u (ses_id=%llu)\n",  /* SID:47 */
    [LA_F48] = "MSG_REQ resent, '%s' -> '%s', sid=%u, attempt %d/%d (ses_id=%llu)\n",  /* SID:48 */
    [LA_F49] = "MSG_RESP gave up after %d retries, sid=%u (ses_id=%llu)\n",  /* SID:49 */
    [LA_F50] = "MSG_RESP resent back to '%s', sid=%u, attempt %d/%d (ses_id=%llu)\n",  /* SID:50 */
    [LA_F51] = "% NAT probe disabled (bind failed)\n",  /* SID:51 */
    [LA_F52] = "NAT probe socket listening on port %d\n",  /* SID:52 */
    [LA_F53] = "NAT probe: %s (port %d)\n",  /* SID:53 */
    [LA_F54] = "P2P Signaling Server listening on port %d (TCP + UDP)...\n",  /* SID:54 */
    [LA_F55] = "PEER_INFO resent, %s <-> %s, attempt %d/%d (ses_id=%llu)\n",  /* SID:55 */
    [LA_F56] = "PEER_INFO retransmit failed: %s <-> %s (gave up after %d tries)\n",  /* SID:56 */
    [LA_F57] = "Pairing complete: '%.*s'(%d cands) <-> '%.*s'(%d cands)\n",  /* SID:57 */
    [LA_F58] = "Relay %s seq=%u: '%s' -> '%s' (ses_id=%llu)\n",  /* SID:58 */
    [LA_F59] = "Relay support: %s\n",  /* SID:59 */
    [LA_F60] = "Send %s: base_index=%u, cands=%d, ses_id=%llu, peer='%s'\n",  /* SID:60 */
    [LA_F61] = "Send %s: mapped=%s:%d\n",  /* SID:61 */
    [LA_F62] = "Send %s: peer='%s', reason=%s, ses_id=%llu\n",  /* SID:62 */
    [LA_F63] = "Send %s: ses_id=%llu, peer='%s'\n",  /* SID:63 */
    [LA_F64] = "Send %s: ses_id=%llu, sid=%u, msg=%u, data_len=%d, peer='%s'\n",  /* SID:64 */
    [LA_F65] = "Send %s: ses_id=%llu, sid=%u, peer='%s', flags=0x%02x, code=%u, data_len=%d\n",  /* SID:65 */
    [LA_F66] = "Send %s: ses_id=%llu, sid=%u, peer='%s'\n",  /* SID:66 */
    [LA_F67] = "Send %s: ses_id=%llu, sid=%u, status=%u\n",  /* SID:67 */
    [LA_F68] = "Send %s: status=%s, max_cands=%d, relay=%s, msg=%s, public=%s:%d, probe=%d, ses_id=%llu, inst_id=%u\n",  /* SID:68 */
    [LA_F69] = "Send %s: status=error (no slot available)\n",  /* SID:69 */
    [LA_F70] = "Starting P2P signal server on port %d\n",  /* SID:70 */
    [LA_F71] = "Timeout & cleanup for pair '%s' -> '%s' (inactive for %.1f seconds)\n",  /* SID:71 */
    [LA_F72] = "Unknown packet type 0x%02x from %s\n",  /* SID:72 */
    [LA_F73] = "[Relay] %s for ses_id=%llu: peer unavailable (dropped)\n",  /* SID:73 */
    [LA_F74] = "[Relay] %s for unknown ses_id=%llu (dropped)\n",  /* SID:74 */
    [LA_F75] = "[Relay] %s seq=%u: '%s' -> '%s' (ses_id=%llu)\n",  /* SID:75 */
    [LA_F76] = "[Relay] %s seq=0 from client %s (server-only, dropped)\n",  /* SID:76 */
    [LA_F77] = "[Relay] %s: '%s' -> '%s' (ses_id=%llu)\n",  /* SID:77 */
    [LA_F78] = "[Relay] %s: bad payload(len=%zu)\n",  /* SID:78 */
    [LA_F163] = "[Relay] %s: missing SESSION flag, dropped\n",  /* SID:163 */
    [LA_F79] = "[TCP]   → Forwarded OFFER from '%s' (%d candidates, %d bytes)\n",  /* SID:79 */
    [LA_F80] = "[TCP]   → Sent empty OFFER from '%s' (storage full, reverse connect)\n",  /* SID:80 */
    [LA_F81] = "[TCP] All pending candidates flushed to '%s'\n",  /* SID:81 */
    [LA_F82] = "[TCP] Cached %d candidates for offline user '%s' (total=%d/%d)\n",  /* SID:82 */
    [LA_F83] = "[TCP] Cached %d candidates for offline user '%s', storage now FULL (%d/%d)\n",  /* SID:83 */
    [LA_F84] = "[TCP] Cannot allocate slot for offline user '%s'\n",  /* SID:84 */
    [LA_F85] = "[TCP] E: Invalid magic from peer '%s'\n",  /* SID:85 */
    [LA_F86] = "[TCP] Failed to receive payload from %s\n",  /* SID:86 */
    [LA_F87] = "[TCP] Failed to receive target name from %s\n",  /* SID:87 */
    [LA_F88] = "[TCP] Failed to send CONNECT_ACK to %s (sent_hdr=%d, sent_payload=%d)\n",  /* SID:88 */
    [LA_F89] = "[TCP] Flushing %d pending candidates from '%s' to '%s'...\n",  /* SID:89 */
    [LA_F90] = "[TCP] I: Peer '%s' logged in\n",  /* SID:90 */
    [LA_F91] = "% [TCP] Max peers reached, rejecting connection\n",  /* SID:91 */
    [LA_F92] = "[TCP] Merged %d pending candidates from offline slot (sender='%s') into online slot for '%s'\n",  /* SID:92 */
    [LA_F93] = "[TCP] New connection from %s:%d\n",  /* SID:93 */
    [LA_F94] = "[TCP] New sender '%s' replaces old sender '%s' (discarding %d old candidates)\n",  /* SID:94 */
    [LA_F95] = "[TCP] Payload too large (%u bytes) from %s\n",  /* SID:95 */
    [LA_F96] = "[TCP] Relaying %s from %s to %s (%u bytes)\n",  /* SID:96 */
    [LA_F97] = "[TCP] Sent %s with %d candidates to '%s' (from '%s')\n",  /* SID:97 */
    [LA_F98] = "[TCP] Sent CONNECT_ACK to %s (status=%d, candidates_acked=%d)\n",  /* SID:98 */
    [LA_F99] = "[TCP] Storage full for '%s' (cached=%d, dropped=%d)\n",  /* SID:99 */
    [LA_F100] = "[TCP] Storage full indication flushed to '%s'\n",  /* SID:100 */
    [LA_F101] = "[TCP] Storage full, connection intent from '%s' to '%s' noted\n",  /* SID:101 */
    [LA_F102] = "[TCP] Storage full, flushing connection intent from '%s' to '%s' (sending empty OFFER)...\n",  /* SID:102 */
    [LA_F103] = "[TCP] Target %s offline, caching candidates...\n",  /* SID:103 */
    [LA_F104] = "[TCP] Unknown message type %d from %s\n",  /* SID:104 */
    [LA_F105] = "[TCP] V: %s sent to '%s'\n",  /* SID:105 */
    [LA_F106] = "[TCP] V: Peer '%s' disconnected\n",  /* SID:106 */
    [LA_F107] = "[TCP] W: Client '%s' timeout (inactive for %.1f seconds)\n",  /* SID:107 */
    [LA_F108] = "[UDP] %s recv from %s, seq=%u, flags=0x%02x, len=%zu\n",  /* SID:108 */
    [LA_F109] = "[UDP] %s send to %s failed(%d)\n",  /* SID:109 */
    [LA_F110] = "[UDP] %s send to %s, seq=%u, flags=0x00, len=%d\n",  /* SID:110 */
    [LA_F111] = "[UDP] %s send to %s, seq=0, flags=0, len=%d\n",  /* SID:111 */
    [LA_F112] = "[UDP] %s send to %s, seq=0, flags=0x%02x, len=%d\n",  /* SID:112 */
    [LA_F113] = "[UDP] %s send to %s:%d failed(%d)\n",  /* SID:113 */
    [LA_F114] = "[UDP] %s send to %s:%d, seq=0, flags=0, len=%d\n",  /* SID:114 */
    [LA_F115] = "[UDP] %s send to %s:%d, seq=0, flags=0x%02x, len=%d, retries=%d\n",  /* SID:115 */
    [LA_F116] = "% net init failed\n",  /* SID:116 */
    [LA_F117] = "probe UDP bind failed(%d)\n",  /* SID:117 */
    [LA_F118] = "select failed(%d)\n",  /* SID:118 */
    [LA_S232] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:232 disabled */
    [LA_S231] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:231 disabled */
    [LA_S230] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:230 disabled */
    [LA_S229] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:229 disabled */
    [LA_S228] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:228 disabled */
    [LA_S227] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:227 disabled */
    [LA_S226] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:226 disabled */
    [LA_S225] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:225 disabled */
    [LA_S224] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:224 disabled */
    [LA_S223] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:223 disabled */
    [LA_S222] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:222 disabled */
    [LA_S221] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:221 disabled */
    [LA_S220] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:220 disabled */
    [LA_S219] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:219 disabled */
    [LA_S218] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:218 disabled */
    [LA_S217] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:217 disabled */
    [LA_S216] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:216 disabled */
    [LA_S215] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:215 disabled */
    [LA_S214] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:214 disabled */
    [LA_S213] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:213 disabled */
    [LA_S212] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:212 disabled */
    [LA_S211] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:211 disabled */
    [LA_S210] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:210 disabled */
    [LA_S209] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:209 disabled */
    [LA_S208] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:208 disabled */
    [LA_S207] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:207 disabled */
    [LA_S206] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:206 disabled */
    [LA_S205] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:205 disabled */
    [LA_S204] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:204 disabled */
    [LA_S203] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:203 disabled */
    [LA_S202] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:202 disabled */
    [LA_S201] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:201 disabled */
    [LA_S200] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:200 disabled */
    [LA_S199] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:199 disabled */
    [LA_S198] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:198 disabled */
    [LA_S197] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:197 disabled */
    [LA_S196] = "Description:\n  P2P signaling server supporting both COMPACT (UDP) and RELAY (TCP) modes.\n  - COMPACT: Stateless UDP signaling with integrated candidate exchange\n  - RELAY:   Stateful TCP signaling for ICE/STUN/TURN architecture\n\nExamples:\n  $0                              # Default: port 9333, no probe, no relay\n  $0 -p 8888                      # Listen on port 8888\n  $0 -p 8888 -P 8889              # Port 8888, probe port 8889\n  $0 -p 8888 -P 8889 --relay      # Full config with relay support\n  $0 --cn -p 8888                 # Chinese language\n\nNote: Run without arguments to use default configuration (port 9333)",  /* SID:196 disabled */
};

/* 语言初始化函数（自动生成，请勿修改）*/
void LA_server_init(void) {
    LA_RID = lang_def(s_lang_en, sizeof(s_lang_en) / sizeof(s_lang_en[0]), LA_FMT_START);
}
